### ISSUE TITLE
xbps-install fails when current working directory does not exist

### ISSUE THREAD

**Issue by freshprince** [voidlinux/xbps#235] opened 2017-03-06 11:30 UTC
To reproduce (as root):

    cd /tmp
    mkdir test
    cd test
    rmdir ../test
    xbps-install -Su

Output:

    ERROR: Failed to initialize libxbps: Operation not supported

**Comment by Gottox** [comment] 2017-03-06 11:40
Duplicate of #158

**Closed by Gottox** 2017-03-06 11:40 UTC
